# -*- coding: utf-8 -*-
"""READMEDEEP..

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBUWXBcI0toQB-MfW38tkpHTD8gisOrV

# Brain Tumor MRI Classification using CNN

## Project Overview
This project focuses on classifying brain MRI images into four categories:
- Glioma
- Meningioma
- Pituitary Tumor
- No Tumor

A Convolutional Neural Network (CNN) model was implemented using transfer learning with the VGG16 architecture to improve classification accuracy and efficiency.

## Technologies Used
- Python
- TensorFlow / Keras
- VGG16 (Transfer Learning)
- NumPy
- Matplotlib
- Google Colab

## Model Approach
- Data preprocessing and normalization
- Data augmentation
- Transfer learning using pretrained VGG16
- Fine-tuning final layers
- Model evaluation using accuracy metrics

## Results
The model achieved high classification accuracy in distinguishing between different tumor types, demonstrating the effectiveness of CNN-based medical image analysis.

## Future Improvements
- Hyperparameter tuning
- Deploying the model using Flask or Streamlit
- Expanding dataset size

## Author
Kenan  
AI & Robotics Engineering Student  
Al-Balqa Applied University
"""